<marquee><b><i><center><h1>
NUMPY = NUMERICAL PYTHON
</marquee>


<img src="https://cdn.educba.com/academy/wp-content/uploads/2020/01/What-is-NumPy-in-Python.jpg.webp" height="120" width="300" align= "center"/>


NumPy is a short form for Numerical Python, which is applied for scientific programming in Python, especially for numbers.<br> It comprises multidimensional objects in arrays and a package of integrating tools for Python implementation.<br> It is basically a mix of C and Python used as an alternative for traditionally used MATLAB programming, where data in the form of numerals are treated as arrays for multidimensional functions and rearrangement operations.


<img src="https://i.imgflip.com/6mv4z9.jpg" height="300" width=350 />

<br>

## Load The Library

In [1]:
import numpy

In [2]:
import numpy as np

<img src="https://pics.me.me/1-import-numpy-1-import-numpy-as-np-there-is-31232276.png" width="300" height="340">

## Numpy Array Creation 

In [61]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [10]:
# Display the type of an object
type(list1)

list

In [11]:
#Convert list to Numpy Array
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [12]:
# Display type of an object
type(arr1)

numpy.ndarray

In [13]:
#Datatype of array
arr1.dtype

dtype('int32')

In [84]:
arr = np.array([1,2,3,4,5,6,6,7])
arr

array([1, 2, 3, 4, 5, 6, 6, 7])

In [14]:
# Generate evenly spaced numbers (space =1) between 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## How to find all even number in C using array?? 

In [25]:
# #include<stdio.h>
# #include<conio.h>
# int main()
# {
#     int arr[10], i;
#     printf("Enter any 10 array elements: ");
#     for(i=0; i<10; i++)
#         scanf("%d", &arr[i]);
#     printf("\nAll Even Array elements are:\n");
#     for(i=0; i<10; i++)
#     {
#         if(arr[i]%2==0)
#         {
#             printf("%d ", arr[i]);
#         }
#     }
#     getch();
#     return 0;
# }

<img src="https://img.ifunny.co/images/9de9a8180790b5f18412d0ff8ba9b11ee9e05cc9112132970641b35beb149479_1.webp" height="300" width="250" />

In [17]:
# Generate numbers between 0 to 100 with a space of 10
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
arr = np.arange(0,101)
print(arr)
print(arr[0:101:2])

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


<img src="https://i.imgflip.com/6dfgvg.jpg" height=200 width=200 />

## Shape Size Dimension Length of an Array 

In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
arr.shape

(10,)

In [30]:
arr.size

10

In [31]:
arr.ndim

1

In [32]:
len(arr)

10

#  Different Types Of ARRAYS

In [33]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
# Generate an array of ones with given shape
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [35]:
# Repeat 10 five times in an array
arr = np.repeat(10,5)
print(arr)

[10 10 10 10 10]


In [36]:
# Repeat each element in array 'a' thrice
a= np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [37]:
# Generate evenly spaced 4 numbers between 10 to 20.
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [38]:
# Create an array of random values
np.random.random(4)

array([0.95929896, 0.39204808, 0.06025652, 0.99988588])

# Operations on an Array

In [40]:
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [41]:
# Sum of all elements in an array
arr2.sum()

190

In [42]:
# Cumulative Sum
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [43]:
# Find Minimum number in an array
arr2.min()

1

In [44]:
# Find MAX number in an array
arr2.max()

19

In [45]:
# Find INDEX of Minimum number in an array
arr2.argmin()

0

In [47]:
# Find INDEX of MAX number in an array
arr2.argmax()

18

In [48]:
# Find mean of all numbers in an array
arr2.mean()

10.0

In [49]:
# Find median of all numbers present in arr2
np.median(arr2)

10.0

In [50]:
# Variance
np.var(arr2)

30.0

In [51]:
# Standard deviation
np.std(arr2)

5.477225575051661

# Operations on a 2D Array

In [52]:
A = np.array([[1,2,3,0] , [5,6,7,22] , [10 , 11 , 1 ,13] , [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [53]:
# SUM of all numbers in a 2D array
A.sum()

129

In [54]:
# MAX number in a 2D array
A.max()

22

In [55]:
# Minimum
A.min()

0

In [56]:
# Column wise mimimum value 
np.amin(A, axis=0)

array([1, 2, 1, 0])

In [57]:
# Row wise mimimum value 
np.amin(A, axis=1)

array([0, 5, 1, 3])

In [58]:
# Mean of all numbers in a 2D array
A.mean()

8.0625

In [59]:
# Median
np.median(A)

6.5

In [60]:
# Enumerate for Numpy 2D Arrays
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


# Reading elements of an array

In [65]:
a = np.array([7,5,3,9,0,2])
print(a)

[7 5 3 9 0 2]


In [66]:
print(a[1:])
print(a[1:4])
print(a[-1])
print(a[-3])
print(a[-3:-1])

[5 3 9 0 2]
[5 3 9]
2
9
[9 0]


# Sorting Array

In [67]:
a = np.array([10,5,2,22,12,92,17,33])
print(np.sort(a))

[ 2  5 10 12 17 22 33 92]


In [69]:
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15]])
a3


array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [70]:
# Sort along rows
np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [71]:
# Sort along columns
np.sort(a3,axis =0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

# Matrix Creation

In [72]:
# Create a 4x4 matrix
Arr1 = np.array([[1,2,3,4] , [5,6,7,8] , [10 , 11 , 12 ,13] , [14,15,16,17]])
Arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [74]:
# Shape of Matrix
Arr1.shape

(4, 4)

In [75]:
# Generate a 4x4 zero matrix
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
Arr1.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17]])

# Diagonal Matrix

In [81]:
# Diagonal Matrix : https://en.wikipedia.org/wiki/Diagonal_matrix

D = np.diag([1,2,3,4,5,6,7,8])
D

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [82]:
# Traingular Matrices (lower & Upper triangular matrix) : https://en.wikipedia.org/wiki/Triangular_matrix

M = np.random.randn(5,5)
U = np.triu(M)
L = np.tril(M)
print("lower triangular matrix - \n" , M)
print("\n")


print("lower triangular matrix - \n" , L)
print("\n")

print("Upper triangular matrix - \n" , U)

lower triangular matrix - 
 [[ 0.10585726 -0.77996893  0.60227775  1.01222792 -0.07310065]
 [-3.17816021  0.33524704 -1.12765373 -0.15327757  0.88480712]
 [ 0.60139177 -0.10660807  1.74191748 -1.23347924  0.17435671]
 [ 1.90257931  0.10073991  0.47213853 -2.34574567 -1.09253303]
 [-2.90130529  0.33418864 -0.11243791 -0.4095002   0.84288781]]


lower triangular matrix - 
 [[ 0.10585726  0.          0.          0.          0.        ]
 [-3.17816021  0.33524704  0.          0.          0.        ]
 [ 0.60139177 -0.10660807  1.74191748  0.          0.        ]
 [ 1.90257931  0.10073991  0.47213853 -2.34574567  0.        ]
 [-2.90130529  0.33418864 -0.11243791 -0.4095002   0.84288781]]


Upper triangular matrix - 
 [[ 0.10585726 -0.77996893  0.60227775  1.01222792 -0.07310065]
 [ 0.          0.33524704 -1.12765373 -0.15327757  0.88480712]
 [ 0.          0.          1.74191748 -1.23347924  0.17435671]
 [ 0.          0.          0.         -2.34574567 -1.09253303]
 [ 0.          0.          0

# Transpose of a Matrix

In [83]:

M = np.array([[1,2,3],[4,-3,6],[7,8,0]])

print("\n Matrix (M)  ==>  \n", M)

print("\nTranspose of M ==>  \n", np.transpose(M))

# OR

print("\nTranspose of M ==>  \n", M.T)


 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Transpose of M ==>  
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]

Transpose of M ==>  
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


# Sum of all elements in a matrix

In [85]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n Matrix (N)  ==>  \n", N)


print ("Sum of all elements in a Matrix  ==>")
print (np.sum(N))


 Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Sum of all elements in a Matrix  ==>
18


# Column-Wise Addition

In [86]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n Matrix (N)  ==>  \n", N)

print ("Column-Wise summation ==> ")
print (np.sum(N,axis=0))


 Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Column-Wise summation ==> 
[6 6 6]


# Row-Wise Addition

In [87]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n Matrix (N)  ==>  \n", N)

print ("Row-Wise summation  ==>")
print (np.sum(N,axis=1))


 Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Row-Wise summation  ==>
[3 6 9]
